export const ExplorerConstants = Object.freeze({
	PADDING_LEFT_SIDEBAR: 20,
	PADDING_RIGHT_SIDEBAR: 20,

	PADDING_TOP_FOOTER: 30,
	PADDING_BOTTOM_FOOTER: 30,

	PADDING_TOP_FOLDER_BAR: 10,
	PADDING_BOTTOM_FOLDER_BAR: 10,

	ICON_SIZE: 24,

	FONT_SIZE: 16,
	FONT_FAMILY: "Recursive",

	INDENTATION_SIZE: 40,
});
