import {
	Hand,
	MousePointer2,
	Type,
	RectangleHorizontal,
	Minus,
	Circle,
	Diamond,
	Cylinder,
	Box,
	Cone,
	Pentagon,
	Slash,
	ChartPie,
	ArrowLeftToLine,
	Pencil,
	Highlighter,
	TableProperties,
	Sword,
	Shapes,
	MoveRight,
	Eraser,
} from "lucide-react";
import { ToolsID } from "./ToolsDetails";

export const ToolsIcon: { [key in ToolsID]: React.ReactNode } = {
	[ToolsID.grab]: <Hand />,
	[ToolsID.cursor]: <MousePointer2 />,
	[ToolsID.text]: <Type />,
	[ToolsID.rectangle]: <RectangleHorizontal />,
	[ToolsID.line]: <Minus />,
	[ToolsID.circle]: <Circle />,
	[ToolsID.directionalLine]: <MoveRight />,
	[ToolsID.segment]: <Minus rotate={90} />,
	[ToolsID.pencil]: <Pencil />,
	[ToolsID.highlighter]: <Highlighter />,
	[ToolsID.lazer]: <Sword />,
	[ToolsID.shape]: <Shapes />,
	[ToolsID.diamond]: <Diamond />,
	[ToolsID.cylinder]: <Cylinder />,
	[ToolsID.box]: <Box />,
	[ToolsID.cone]: <Cone />,
	[ToolsID.pentagon]: <Pentagon />,
	[ToolsID.chart]: <ChartPie />,
	[ToolsID.slash]: <Slash />,
	[ToolsID.table]: <TableProperties />,
	[ToolsID.arrow]: <ArrowLeftToLine />,
	[ToolsID.eraser]: <Eraser />,
};
