export const NOTES_SUFFIX = "$NOTE$";
export const FOLDERS_SUFFIX = "$FOLDER$";
export const GUEST_USER_ID = "guest@temp.com";

export const LOGIN_POPUP_TIMEOUT = 1000000;

export const DATA_STORAGE_KEY = "DATA_STORAGE_KEY";

export const DETAILS_HANDLE_KEY = "DETAILS_HANDLE_KEY";
export const STRUCTURE_HANDLE_KEY = "STRUCTURE_HANDLE_KEY";
export const CONFIG_HANDLE_KEY = "CONFIG_HANDLE_KEY";
export const PROFILE_HANDLE_KEY = "PROFILE_HANDLE_KEY";
export const PREFERENCES_HANDLE_KEY = "PREFERENCES_HANDLE_KEY";
